// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQJo-RzVceRvkvp05gBx0QzssIb9-8zU',
    appId: '1:564350309447:web:5188d0d56fea6cfcec8d62',
    messagingSenderId: '564350309447',
    projectId: 'assetflow-2643a',
    authDomain: 'assetflow-2643a.firebaseapp.com',
    storageBucket: 'assetflow-2643a.firebasestorage.app',
    measurementId: 'G-NZBCE40E7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMrVt6s1ZmEnAAXwD_dGu2qjOzPQWvp4',
    appId: '1:564350309447:android:eba6984d15a82566ec8d62',
    messagingSenderId: '564350309447',
    projectId: 'assetflow-2643a',
    storageBucket: 'assetflow-2643a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCIkOP1OChW_MGP_Iz2n4OmlRDbYCsg0',
    appId: '1:564350309447:ios:01c37a076cf5534aec8d62',
    messagingSenderId: '564350309447',
    projectId: 'assetflow-2643a',
    storageBucket: 'assetflow-2643a.firebasestorage.app',
    iosBundleId: 'com.example.swechaassetflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCIkOP1OChW_MGP_Iz2n4OmlRDbYCsg0',
    appId: '1:564350309447:ios:01c37a076cf5534aec8d62',
    messagingSenderId: '564350309447',
    projectId: 'assetflow-2643a',
    storageBucket: 'assetflow-2643a.firebasestorage.app',
    iosBundleId: 'com.example.swechaassetflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIQJo-RzVceRvkvp05gBx0QzssIb9-8zU',
    appId: '1:564350309447:web:0bf80ba3a2319ea6ec8d62',
    messagingSenderId: '564350309447',
    projectId: 'assetflow-2643a',
    authDomain: 'assetflow-2643a.firebaseapp.com',
    storageBucket: 'assetflow-2643a.firebasestorage.app',
    measurementId: 'G-QTP6ZLSZ3W',
  );
}
